// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../../include/ui/ui.h"

lv_obj_t * ui_Screen1 = NULL;
lv_obj_t * ui_PanelGear = NULL;
lv_obj_t * ui_gear = NULL;
lv_obj_t * ui_PanelRPM = NULL;
lv_obj_t * ui_rpm = NULL;
lv_obj_t * ui_PanelBATT = NULL;
lv_obj_t * ui_battvoltlabel = NULL;
lv_obj_t * ui_battvolt = NULL;
lv_obj_t * ui_PanelETC = NULL;
lv_obj_t * ui_ect = NULL;
lv_obj_t * ui_ECTlabel = NULL;
lv_obj_t * ui_PanelSHUTDOWN = NULL;
lv_obj_t * ui_SHUTDOWN_LABEL = NULL;
lv_obj_t * ui_shutdown = NULL;
lv_obj_t * ui_PanelFAN = NULL;
lv_obj_t * ui_FANLabel = NULL;
lv_obj_t * ui_fan = NULL;
// event funtions

// build funtions

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_PanelGear = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_PanelGear, 229);
    lv_obj_set_height(ui_PanelGear, 290);
    lv_obj_set_x(ui_PanelGear, 0);
    lv_obj_set_y(ui_PanelGear, 41);
    lv_obj_set_align(ui_PanelGear, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelGear, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_gear = lv_label_create(ui_PanelGear);
    lv_obj_set_width(ui_gear, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_gear, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_gear, 2);
    lv_obj_set_y(ui_gear, 6);
    lv_obj_set_align(ui_gear, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_gear, LV_LABEL_LONG_DOT);
    lv_label_set_text(ui_gear, "N");
    lv_obj_set_style_text_color(ui_gear, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_gear, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_gear, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_gear, &ui_font_Consolas350, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelRPM = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_PanelRPM, 778);
    lv_obj_set_height(ui_PanelRPM, 116);
    lv_obj_set_x(ui_PanelRPM, 0);
    lv_obj_set_y(ui_PanelRPM, -173);
    lv_obj_set_align(ui_PanelRPM, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelRPM, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_rpm = lv_label_create(ui_PanelRPM);
    lv_obj_set_width(ui_rpm, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_rpm, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_rpm, -2);
    lv_obj_set_y(ui_rpm, 3);
    lv_obj_set_align(ui_rpm, LV_ALIGN_CENTER);
    lv_label_set_text(ui_rpm, "12800");
    lv_obj_set_style_text_letter_space(ui_rpm, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_rpm, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_rpm, &ui_font_Consolas150, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelBATT = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_PanelBATT, 258);
    lv_obj_set_height(ui_PanelBATT, 130);
    lv_obj_set_x(ui_PanelBATT, -255);
    lv_obj_set_y(ui_PanelBATT, -37);
    lv_obj_set_align(ui_PanelBATT, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelBATT, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_battvoltlabel = lv_label_create(ui_PanelBATT);
    lv_obj_set_width(ui_battvoltlabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_battvoltlabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_battvoltlabel, -88);
    lv_obj_set_y(ui_battvoltlabel, 1);
    lv_obj_set_align(ui_battvoltlabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_battvoltlabel, "VBATT");
    lv_obj_set_style_text_color(ui_battvoltlabel, lv_color_hex(0xFF8500), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_battvoltlabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_battvoltlabel, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_battvolt = lv_label_create(ui_PanelBATT);
    lv_obj_set_width(ui_battvolt, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_battvolt, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_battvolt, 34);
    lv_obj_set_y(ui_battvolt, 2);
    lv_obj_set_align(ui_battvolt, LV_ALIGN_CENTER);
    lv_label_set_text(ui_battvolt, "13.64");
    lv_obj_set_style_text_font(ui_battvolt, &ui_font_Consolas60, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelETC = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_PanelETC, 258);
    lv_obj_set_height(ui_PanelETC, 128);
    lv_obj_set_x(ui_PanelETC, 254);
    lv_obj_set_y(ui_PanelETC, -38);
    lv_obj_set_align(ui_PanelETC, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelETC, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ect = lv_label_create(ui_PanelETC);
    lv_obj_set_width(ui_ect, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ect, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ect, 58);
    lv_obj_set_y(ui_ect, 3);
    lv_obj_set_align(ui_ect, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ect, "80");
    lv_obj_set_style_text_font(ui_ect, &ui_font_Consolas60, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ECTlabel = lv_label_create(ui_PanelETC);
    lv_obj_set_width(ui_ECTlabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ECTlabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ECTlabel, -94);
    lv_obj_set_y(ui_ECTlabel, 1);
    lv_obj_set_align(ui_ECTlabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ECTlabel, "ECT");
    lv_obj_set_style_text_color(ui_ECTlabel, lv_color_hex(0xFF8500), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ECTlabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ECTlabel, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelSHUTDOWN = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_PanelSHUTDOWN, 259);
    lv_obj_set_height(ui_PanelSHUTDOWN, 52);
    lv_obj_set_x(ui_PanelSHUTDOWN, -256);
    lv_obj_set_y(ui_PanelSHUTDOWN, 63);
    lv_obj_set_align(ui_PanelSHUTDOWN, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelSHUTDOWN, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_SHUTDOWN_LABEL = lv_label_create(ui_PanelSHUTDOWN);
    lv_obj_set_width(ui_SHUTDOWN_LABEL, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SHUTDOWN_LABEL, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SHUTDOWN_LABEL, -67);
    lv_obj_set_y(ui_SHUTDOWN_LABEL, -1);
    lv_obj_set_align(ui_SHUTDOWN_LABEL, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SHUTDOWN_LABEL, "SHUTDOWN");
    lv_obj_set_style_text_color(ui_SHUTDOWN_LABEL, lv_color_hex(0xFF8500), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SHUTDOWN_LABEL, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SHUTDOWN_LABEL, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_shutdown = lv_label_create(ui_PanelSHUTDOWN);
    lv_obj_set_width(ui_shutdown, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_shutdown, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_shutdown, 72);
    lv_obj_set_y(ui_shutdown, 0);
    lv_obj_set_align(ui_shutdown, LV_ALIGN_CENTER);
    lv_label_set_text(ui_shutdown, "OFF");
    lv_obj_set_style_text_font(ui_shutdown, &ui_font_Consolas35, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelFAN = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_PanelFAN, 255);
    lv_obj_set_height(ui_PanelFAN, 52);
    lv_obj_set_x(ui_PanelFAN, 254);
    lv_obj_set_y(ui_PanelFAN, 61);
    lv_obj_set_align(ui_PanelFAN, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelFAN, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_FANLabel = lv_label_create(ui_PanelFAN);
    lv_obj_set_width(ui_FANLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_FANLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_FANLabel, -91);
    lv_obj_set_y(ui_FANLabel, 9);
    lv_obj_set_align(ui_FANLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_FANLabel, "FAN\n");
    lv_obj_set_style_text_color(ui_FANLabel, lv_color_hex(0xFF8500), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_FANLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_FANLabel, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_fan = lv_label_create(ui_PanelFAN);
    lv_obj_set_width(ui_fan, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_fan, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_fan, 58);
    lv_obj_set_y(ui_fan, -1);
    lv_obj_set_align(ui_fan, LV_ALIGN_CENTER);
    lv_label_set_text(ui_fan, "OFF");
    lv_obj_set_style_text_font(ui_fan, &ui_font_Consolas35, LV_PART_MAIN | LV_STATE_DEFAULT);

}

void ui_Screen1_screen_destroy(void)
{
    if(ui_Screen1) lv_obj_del(ui_Screen1);

    // NULL screen variables
    ui_Screen1 = NULL;
    ui_PanelGear = NULL;
    ui_gear = NULL;
    ui_PanelRPM = NULL;
    ui_rpm = NULL;
    ui_PanelBATT = NULL;
    ui_battvoltlabel = NULL;
    ui_battvolt = NULL;
    ui_PanelETC = NULL;
    ui_ect = NULL;
    ui_ECTlabel = NULL;
    ui_PanelSHUTDOWN = NULL;
    ui_SHUTDOWN_LABEL = NULL;
    ui_shutdown = NULL;
    ui_PanelFAN = NULL;
    ui_FANLabel = NULL;
    ui_fan = NULL;

}
